# Generated by Django 3.0.2 on 2020-02-02 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20200202_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='color',
            field=models.CharField(default='red', max_length=20),
        ),
        migrations.AddField(
            model_name='note',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='note',
            name='flavor',
            field=models.CharField(default='tangerine', max_length=20),
            preserve_default=False,
        ),
    ]
