# Generated by Django 3.0.2 on 2020-02-02 03:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20200202_0338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Renote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('retitle', models.CharField(max_length=200)),
                ('recontent', models.TextField(default='Renote default message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
